Feat/st 15
VirtoCommerce/vue-starter-theme pull request #14
Opened 2021-12-02 16:37 UTC by Flanker72

Responsive Main page with header and footer for all screen sizes

2021-12-02 20:06 UTC, ilyawzrd requested changes

2021-12-02 20:12 UTC, ilyawzrd commented
@Flanker72 Can you also rename PR, so it will have a meaningful name in the commit history.
And one more thing - 'All products' dropdown on mobile version isn't toggling back and forth, only opens

2021-12-03 08:55 UTC, ilyawzrd approved these changes

2021-12-03 09:01 UTC, trueboroda approved these changes

2021-12-03 09:05 UTC, merged