feat: add order details page
VirtoCommerce/vue-starter-theme pull request #50
Opened 2022-02-09 12:34 UTC by ilyawzrd

Description:

--

QA-test: ST-193

Demo-test: ST-194

Download artifact URL:

2022-02-09 14:42 UTC, tatarincev requested changes

2022-02-09 14:44 UTC, Flanker72 commented on client-app/pages/account/order-details.vue
> +const itemsPerPage = ref(4);
"Magic numbers" should be defined as constants in UPPERCASE in the top of the script:
```
const MAX_ITEMS = 4;
...
const itemsPerPage = ref(MAX_ITEMS);
```

2022-02-09 14:47 UTC, Flanker72 commented on client-app/shared/checkout/components/order-summary.vue
> +                  <span>{{ cart.currency?.symbol }}{{ typeof discount?.amount === 'object' && discount?.amount !== null ? discount?.amount.amount : discount?.amount }}</span>
Maybe it's better to create a computed prop instead. Template shouldn't content complex logic.

2022-02-10 07:20 UTC, Flanker72 approved these changes

2022-02-10 10:06 UTC, merged